name: Deploy GitHub Pages from subfolder

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload subfolder to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: proyecto_html_css

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

